/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BooksRouteImport } from './routes/books'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CommerceRouteImport } from './routes/commerce'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as WriteRouteImport } from './routes/write'
import { Route as BookBookIdRouteImport } from './routes/book.$bookId'
import { Route as BooksLibraryRouteImport } from './routes/books.library'
import { Route as CommunitiesCommunityIdRouteImport } from './routes/communities.$communityId'
import { Route as DirectionLayerRouteImport } from './routes/direction.$layer'
import { Route as FeedLaneRouteImport } from './routes/feed.$lane'
import { Route as MessagesThreadIdRouteImport } from './routes/messages.$threadId'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as StudioMediaRouteImport } from './routes/studio.media'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as WikiArticleIdRouteImport } from './routes/wiki.$articleId'
import { Route as ReadBookIdChapterIdRouteImport } from './routes/read.$bookId.$chapterId'
import { Route as UUsernameShopRouteImport } from './routes/u.$username.shop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CommerceRoute = CommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookIdRoute = BookBookIdRouteImport.update({
  id: '/book/$bookId',
  path: '/book/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksLibraryRoute = BooksLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => BooksRoute,
} as any)
const CommunitiesCommunityIdRoute = CommunitiesCommunityIdRouteImport.update({
  id: '/$communityId',
  path: '/$communityId',
  getParentRoute: () => CommunitiesRoute,
} as any)
const DirectionLayerRoute = DirectionLayerRouteImport.update({
  id: '/direction/$layer',
  path: '/direction/$layer',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedLaneRoute = FeedLaneRouteImport.update({
  id: '/feed/$lane',
  path: '/feed/$lane',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesThreadIdRoute = MessagesThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => MessagesRoute,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioMediaRoute = StudioMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => StudioRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiArticleIdRoute = WikiArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => WikiRoute,
} as any)
const ReadBookIdChapterIdRoute = ReadBookIdChapterIdRouteImport.update({
  id: '/read/$bookId/$chapterId',
  path: '/read/$bookId/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameShopRoute = UUsernameShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => UUsernameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/books': typeof BooksRouteWithChildren
  '/cart': typeof CartRoute
  '/commerce': typeof CommerceRoute
  '/communities': typeof CommunitiesRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRouteWithChildren
  '/wiki': typeof WikiRouteWithChildren
  '/write': typeof WriteRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/books/library': typeof BooksLibraryRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/direction/$layer': typeof DirectionLayerRoute
  '/feed/$lane': typeof FeedLaneRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/studio/media': typeof StudioMediaRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/wiki/$articleId': typeof WikiArticleIdRoute
  '/read/$bookId/$chapterId': typeof ReadBookIdChapterIdRoute
  '/u/$username/shop': typeof UUsernameShopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/books': typeof BooksRouteWithChildren
  '/cart': typeof CartRoute
  '/commerce': typeof CommerceRoute
  '/communities': typeof CommunitiesRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRouteWithChildren
  '/wiki': typeof WikiRouteWithChildren
  '/write': typeof WriteRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/books/library': typeof BooksLibraryRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/direction/$layer': typeof DirectionLayerRoute
  '/feed/$lane': typeof FeedLaneRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/studio/media': typeof StudioMediaRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/wiki/$articleId': typeof WikiArticleIdRoute
  '/read/$bookId/$chapterId': typeof ReadBookIdChapterIdRoute
  '/u/$username/shop': typeof UUsernameShopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/books': typeof BooksRouteWithChildren
  '/cart': typeof CartRoute
  '/commerce': typeof CommerceRoute
  '/communities': typeof CommunitiesRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRouteWithChildren
  '/wiki': typeof WikiRouteWithChildren
  '/write': typeof WriteRoute
  '/book/$bookId': typeof BookBookIdRoute
  '/books/library': typeof BooksLibraryRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/direction/$layer': typeof DirectionLayerRoute
  '/feed/$lane': typeof FeedLaneRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/studio/media': typeof StudioMediaRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/wiki/$articleId': typeof WikiArticleIdRoute
  '/read/$bookId/$chapterId': typeof ReadBookIdChapterIdRoute
  '/u/$username/shop': typeof UUsernameShopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/books'
    | '/cart'
    | '/commerce'
    | '/communities'
    | '/discover'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/search'
    | '/studio'
    | '/wiki'
    | '/write'
    | '/book/$bookId'
    | '/books/library'
    | '/communities/$communityId'
    | '/direction/$layer'
    | '/feed/$lane'
    | '/messages/$threadId'
    | '/product/$productId'
    | '/studio/media'
    | '/u/$username'
    | '/wiki/$articleId'
    | '/read/$bookId/$chapterId'
    | '/u/$username/shop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/books'
    | '/cart'
    | '/commerce'
    | '/communities'
    | '/discover'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/search'
    | '/studio'
    | '/wiki'
    | '/write'
    | '/book/$bookId'
    | '/books/library'
    | '/communities/$communityId'
    | '/direction/$layer'
    | '/feed/$lane'
    | '/messages/$threadId'
    | '/product/$productId'
    | '/studio/media'
    | '/u/$username'
    | '/wiki/$articleId'
    | '/read/$bookId/$chapterId'
    | '/u/$username/shop'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/books'
    | '/cart'
    | '/commerce'
    | '/communities'
    | '/discover'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/search'
    | '/studio'
    | '/wiki'
    | '/write'
    | '/book/$bookId'
    | '/books/library'
    | '/communities/$communityId'
    | '/direction/$layer'
    | '/feed/$lane'
    | '/messages/$threadId'
    | '/product/$productId'
    | '/studio/media'
    | '/u/$username'
    | '/wiki/$articleId'
    | '/read/$bookId/$chapterId'
    | '/u/$username/shop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BooksRoute: typeof BooksRouteWithChildren
  CartRoute: typeof CartRoute
  CommerceRoute: typeof CommerceRoute
  CommunitiesRoute: typeof CommunitiesRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  SearchRoute: typeof SearchRoute
  StudioRoute: typeof StudioRouteWithChildren
  WikiRoute: typeof WikiRouteWithChildren
  WriteRoute: typeof WriteRoute
  BookBookIdRoute: typeof BookBookIdRoute
  DirectionLayerRoute: typeof DirectionLayerRoute
  FeedLaneRoute: typeof FeedLaneRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  UUsernameRoute: typeof UUsernameRouteWithChildren
  ReadBookIdChapterIdRoute: typeof ReadBookIdChapterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commerce': {
      id: '/commerce'
      path: '/commerce'
      fullPath: '/commerce'
      preLoaderRoute: typeof CommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookId': {
      id: '/book/$bookId'
      path: '/book/$bookId'
      fullPath: '/book/$bookId'
      preLoaderRoute: typeof BookBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/library': {
      id: '/books/library'
      path: '/library'
      fullPath: '/books/library'
      preLoaderRoute: typeof BooksLibraryRouteImport
      parentRoute: typeof BooksRoute
    }
    '/communities/$communityId': {
      id: '/communities/$communityId'
      path: '/$communityId'
      fullPath: '/communities/$communityId'
      preLoaderRoute: typeof CommunitiesCommunityIdRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/direction/$layer': {
      id: '/direction/$layer'
      path: '/direction/$layer'
      fullPath: '/direction/$layer'
      preLoaderRoute: typeof DirectionLayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$lane': {
      id: '/feed/$lane'
      path: '/feed/$lane'
      fullPath: '/feed/$lane'
      preLoaderRoute: typeof FeedLaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$threadId': {
      id: '/messages/$threadId'
      path: '/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof MessagesThreadIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/media': {
      id: '/studio/media'
      path: '/media'
      fullPath: '/studio/media'
      preLoaderRoute: typeof StudioMediaRouteImport
      parentRoute: typeof StudioRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$articleId': {
      id: '/wiki/$articleId'
      path: '/$articleId'
      fullPath: '/wiki/$articleId'
      preLoaderRoute: typeof WikiArticleIdRouteImport
      parentRoute: typeof WikiRoute
    }
    '/read/$bookId/$chapterId': {
      id: '/read/$bookId/$chapterId'
      path: '/read/$bookId/$chapterId'
      fullPath: '/read/$bookId/$chapterId'
      preLoaderRoute: typeof ReadBookIdChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/shop': {
      id: '/u/$username/shop'
      path: '/shop'
      fullPath: '/u/$username/shop'
      preLoaderRoute: typeof UUsernameShopRouteImport
      parentRoute: typeof UUsernameRoute
    }
  }
}

interface BooksRouteChildren {
  BooksLibraryRoute: typeof BooksLibraryRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksLibraryRoute: BooksLibraryRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

interface CommunitiesRouteChildren {
  CommunitiesCommunityIdRoute: typeof CommunitiesCommunityIdRoute
}

const CommunitiesRouteChildren: CommunitiesRouteChildren = {
  CommunitiesCommunityIdRoute: CommunitiesCommunityIdRoute,
}

const CommunitiesRouteWithChildren = CommunitiesRoute._addFileChildren(
  CommunitiesRouteChildren,
)

interface MessagesRouteChildren {
  MessagesThreadIdRoute: typeof MessagesThreadIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesThreadIdRoute: MessagesThreadIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface StudioRouteChildren {
  StudioMediaRoute: typeof StudioMediaRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioMediaRoute: StudioMediaRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

interface WikiRouteChildren {
  WikiArticleIdRoute: typeof WikiArticleIdRoute
}

const WikiRouteChildren: WikiRouteChildren = {
  WikiArticleIdRoute: WikiArticleIdRoute,
}

const WikiRouteWithChildren = WikiRoute._addFileChildren(WikiRouteChildren)

interface UUsernameRouteChildren {
  UUsernameShopRoute: typeof UUsernameShopRoute
}

const UUsernameRouteChildren: UUsernameRouteChildren = {
  UUsernameShopRoute: UUsernameShopRoute,
}

const UUsernameRouteWithChildren = UUsernameRoute._addFileChildren(
  UUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BooksRoute: BooksRouteWithChildren,
  CartRoute: CartRoute,
  CommerceRoute: CommerceRoute,
  CommunitiesRoute: CommunitiesRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  MarketplaceRoute: MarketplaceRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  SearchRoute: SearchRoute,
  StudioRoute: StudioRouteWithChildren,
  WikiRoute: WikiRouteWithChildren,
  WriteRoute: WriteRoute,
  BookBookIdRoute: BookBookIdRoute,
  DirectionLayerRoute: DirectionLayerRoute,
  FeedLaneRoute: FeedLaneRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  UUsernameRoute: UUsernameRouteWithChildren,
  ReadBookIdChapterIdRoute: ReadBookIdChapterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
